### ISSUE TITLE
Receiving warning: CUICatalog: Invalid asset name supplied: ''

### ISSUE THREAD

**Issue by jtressle** [exyte/fan-menu#10]
When an image string is left blank (like in the TaskViewController example), one gets the warning:

> CUICatalog: Invalid asset name supplied: ''

Easy fix is to add:

`if (!button.image.isEmpty) {...}`

around the two places an UIImage is loaded.

Thanks!

**Comment by zapletnev** [comment]
Thanks for reporting @jtressle. The issue is fixed in the master branch.

**Comment by alanjturn** [comment]
how can I find the line of code in my project that is giving this error? Is there a way to do this using the console?
