### ISSUE TITLE
View overlapped

### ISSUE THREAD

**Issue by WayneSKK** [exyte/fan-menu#12]
HI!
I found that when creating a view on the top for menu use, then it will cover the content from the bottom and the bottom view cannot click or slide. Is there an alternative way to make it??

Thank you!!

**Comment by zapletnev** [comment]
Hi @WayneSKK,
Thanks for choosing fan-menu. I will check this issue and let you know what you can do in such use case.

**Comment by zapletnev** [comment]
@WayneSKK I created a ticket in Macaw repository: https://github.com/exyte/Macaw/issues/213

**Comment by ginamterry** [comment]
Any updates on this? I'm using this in a tableview and can't scroll the table where the menu view is positioned.

**Comment by zapletnev** [comment]
@ginamterry this issue is fixed in Macaw. After new Macaw release, we will make fan-menu release including this fix. 

For now, you can use macaw fix: https://github.com/exyte/Macaw/pull/294
And corresponding fan-menu fix: https://github.com/exyte/fan-menu/pull/16
