### ISSUE TITLE
ios Deployment Target for FanMenu

### ISSUE THREAD

**Issue by itali43** [exyte/fan-menu#14]
Thanks for a great library :) 

When I downloaded it I couldn't get it running, had to change the development target for the FanMenu Pod to "iOS 9.1" (it defaults at "iOS 8.0") in the Pods>Targets:FanMenu>BuildSettings>iOS Deployment Target.

For reference here is the error I got: 
`Module file's minimum deployment target is ios9.1 v9.1: /Users/xxxxxxxxxx/Library/Developer/Xcode/DerivedData/FanMenuBase-caahzwnyrbhuevepdjyscebyqvtb/Build/Products/Debug-iphonesimulator/Macaw/Macaw.framework/Modules/Macaw.swiftmodule/x86_64.swiftmodule`

After I swapped that and Cleaned my build it works beautifully. 👍

**Comment by MatrixSenpai** [comment]
Same issue, following this resolved it

**Comment by vhailor13** [comment]
Fixed with 0.7.1 update
