### ISSUE TITLE
iTunes Connect upload error : CFBundleIdentifier Collision  

### ISSUE THREAD

**Issue by remithaunay** [exyte/fan-menu#21]
Uploading my app on iTunes Connect is giving an error with the FanMenu framework used inside, (integrated through Carthage)

ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.exyte.Macaw' under the iOS application 'MyApp.app'."
ERROR ITMS-90205: "Invalid Bundle. The bundle at 'MyApp.app/Frameworks/FanMenu.framework' contains disallowed nested bundles."
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'MyApp.app/Frameworks/FanMenu.framework' contains disallowed file 'Frameworks'."

Is it something that you're aware of ?

**Comment by f3dm76** [comment]
Hello, first of all, thanks for using fan-menu.

Could you please provide your Carthage config? Maybe it contains both Macaw and Fan-menu, and this is why it is added twice. In any case, it would help to take a look at it.

Also, it seems like you are not the only one to encounter a similar issue, did you happen to come across this answer? 
https://stackoverflow.com/questions/29608264/error-itms-90451-cfbundleidentifier-collision-error?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by remithaunay** [comment]
Hello !
thanks for your quick answer.

I figured out the issue and it is indeed because our Carthage configuration contains both frameworks.
Actually, we also use Macaw in our app apart from FanMenu, So I had to remove manually Macaw from FanMenu with a Build Phase script: 

```
cd "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/FanMenu.framework"
rm -fr Frameworks/
```

The best solution would be to not embed Macaw in FanMenu. 
The internet gave me a lot of answers like the one you linked but it's all about extensions. I really think our issue is an edge case and the copy-framework inside a framework should be avoided, as it does not appear to be a good practice

Would you be open to consider removing that ?

**Comment by f3dm76** [comment]
People should be able to just specify fan-menu and use it. They should not be forced to know about its dependencies and manually add them all to their Carthage config. If we remove Macaw dependency from fan-menu, people will be forced to do exactly that. Could you please provide more information as to why you consider this to be a "good practice"?

**Comment by remithaunay** [comment]
Please look at answers from Matt, a Carthage developer, [here](https://github.com/Carthage/Carthage/issues/688#issuecomment-166165355) and where his links send you to.

**Comment by amarunko** [comment]
Hi, @remithaunay , sorry for response delay. I removed Carthage dependencies from the project. I tested with linked binaries, for me, everything works fine. Please, use last changes from the master branch, thanks.
