### ISSUE TITLE
menu not response in iOS 12

### ISSUE THREAD

**Issue by WayneSKK** [exyte/fan-menu#23]
Button seems not working  in iOS 12 properly, all of them are no response .

**Comment by WayneSKK** [comment]
@sverin Not yet. Do you have the same issue?

**Comment by sverin** [comment]
@WayneSKK Yes, but haven't found a solution yet

**Comment by sverin** [comment]
@WayneSKK If I build the Macaw library from master repo it works just fine. The 0.9.2 build from Carthage seems to have some issues resolved in the master version.

**Comment by WayneSKK** [comment]
@sverin How to build from Macaw master? They having same version 0.9.2. I am using CocoaPods.

**Comment by WayneSKK** [comment]
@sverin Finally, I build macaw again and convert swift version to 4.2, then it is working fine again! Thanks!

**Comment by zapletnev** [comment]
It looks like this issue was resolved. Please let me know if you have any questions. Closing for now.
