### ISSUE TITLE
i want to add a label next to every button in menu

### ISSUE THREAD

**Issue by mEldewaik** [exyte/fan-menu#24]
i want to add a label next to every button in menu anyone can help ?

**Comment by amarunko** [comment]
Hi, @mEldewaik. Fan menu doesn't have this possibility from the box, but you can extend the library and send a pull request. For this functional, you can extend FanMenuButton to include button title and add a new node with Text type during buttons nodes initialization (FanMenu class init).

**Comment by amarunko** [comment]
You can use https://github.com/exyte/fan-menu/pull/25 as reference.

**Comment by zapletnev** [comment]
It looks like this issue was closed. Please let me know if you have any questions. Closing for now.
