### ISSUE TITLE
Errors compiling the example.

### ISSUE THREAD

**Issue by mcroker** [exyte/fan-menu#26]
I receive the following warning and error when I try and build the example in Xcode 10.1.

1) Target 'FanMenu' (project 'Pods') has copy command from '/Users/martin/dev/fan-menu/Sources/Info.plist' to '/Users/martin/Library/Developer/Xcode/DerivedData/Example-fykvmcsmliphikcyocogamyeedyl/Build/Products/Debug-iphonesimulator/FanMenu/FanMenu.framework/Info.plist'

2) Target 'FanMenu' (project 'Pods') has process command with output '/Users/martin/Library/Developer/Xcode/DerivedData/Example-fykvmcsmliphikcyocogamyeedyl/Build/Products/Debug-iphonesimulator/FanMenu/FanMenu.framework/Info.plist'

**Comment by amarunko** [comment]
It is build system related bug; you can use legacy build system (XCode-file-project/workspace settings-build system - legacy)

**Comment by zapletnev** [comment]
Please let me know if you have any questions.
Feel free to update the ReadMe and send PR. Closing for now.

**Comment by zapletnev** [comment]
@mcroker sorry for the misunderstanding. We just pushed a fix for this issue.

**Comment by mcroker** [comment]
Many thanks!
