### ISSUE TITLE
I won't close nods after press them

### ISSUE THREAD

**Issue by yoohanna** [exyte/fan-menu#32]
Hi.
There is no delegate for nodes when we pressed one of them.
1- I won't close nodes after I pressed one of them but I want to get id of node that I pressed it.
2- I want to hide mainButton but I can't do that.
3- Is it possible set clear color to main circle of fan-menu?

Thanks.

**Comment by zapletnev** [comment]
Hi @yoohanna,

Thanks for the report. We don't plan these changes in the library. To achieve it you can fork the project and make all the necessary changes.

- To avoid closing the menu. Replace the attribute open from `false` -> `true`: https://github.com/exyte/fan-menu/blob/master/Sources/FanMenu.swift#L335
- To hide the main button, you can change its visibility: `buttonNode.visible = false`
- Use: Color.clear

I am closing this ticket for now. Feel free to reopen if any questions remain.
