### ISSUE TITLE
Build failed after integrated

### ISSUE THREAD

**Issue by libern** [exyte/fan-menu#35]
![image](https://user-images.githubusercontent.com/1830640/53026107-3bd78280-349d-11e9-8336-9e306309eea4.png)

```

Showing All Messages
:-1: Multiple commands produce '/Users/Libern/Library/Developer/Xcode/DerivedData/Sparkle-eluqypnvotfmphgsbcljsqmyugvd/Build/Products/Debug-iphoneos/FanMenu/FanMenu.framework/Info.plist':
1) Target 'FanMenu' (project 'Pods') has copy command from '/Users/Libern/LibernWorking/Projects/Someline/sparkle-ios/Pods/FanMenu/Sources/Info.plist' to '/Users/Libern/Library/Developer/Xcode/DerivedData/Sparkle-eluqypnvotfmphgsbcljsqmyugvd/Build/Products/Debug-iphoneos/FanMenu/FanMenu.framework/Info.plist'
2) Target 'FanMenu' (project 'Pods') has process command with output '/Users/Libern/Library/Developer/Xcode/DerivedData/Sparkle-eluqypnvotfmphgsbcljsqmyugvd/Build/Products/Debug-iphoneos/FanMenu/FanMenu.framework/Info.plist'
```

**Comment by amarunko** [comment]
Hm, okay, we will investigate the issue, for quick fix you can find info plist in project navigator and disable this file for target

**Comment by zapletnev** [comment]
Hi @libern,

Thanks for the report. This issue should be fixed in the master branch. Please do next:
* Pull the latest changes. Hash should be: a38ea41b579266a87114bd165252c8539c4586a5
* Do `pod update` and `pod install` in the Example folder
* Open Example workspace, clean and rebuild the project.

Please let me know if the issue remains. Thanks for using FanMenu!

**Comment by zapletnev** [comment]
@libern sorry for the misunderstanding. If you are using cocoapods to please use the fan-menu master branch. It includes the fix:
```
pod 'FanMenu', :git => 'https://github.com/exyte/fan-menu'
```

Please reopen the ticket if any questions remain.

**Comment by lewis-smith** [comment]
It might be useful to leave this issue open until 

`pod 'FanMenu'`

works again.
