### ISSUE TITLE
XCode update to 10.2 crashes with "This coder requires that replaced objects be returned from initWithCoder:"

### ISSUE THREAD

**Issue by dragosroua** [exyte/fan-menu#40]
The error appears after dropping a FanMenu / UIView on Interface Builder and calling the IBOutlet associated with it.

I think this may be a Macaw related error.

Never mind: updating to Macaw 0.9.5 fixed this.

(Letting this here to the admin to close)

**Comment by mgoldin** [comment]
Works well on version 0.7.3
