### ISSUE TITLE
Background circle reduce to half

### ISSUE THREAD

**Issue by Gagan6696** [exyte/fan-menu#42]
Hello sir,

I want to show half circle rather than full circle.
which code should I need to update ??

**Comment by amarunko** [comment]
Hi, @Gagan6696, you can change FanMenu.swift:

https://github.com/exyte/fan-menu/blob/10b61761da185a1ca05aefccdb46edde7b6c4455/Sources/FanMenu.swift#L189

you can switch here to any shape

**Comment by Gagan6696** [comment]
I already tried this by changing different parameters like reduce radius to half.
But unfortunately nothing will change. 
Could you please define me parameters , which I have to change

**Comment by shipinev** [comment]
Hey @Gagan6696!
I'm sorry for the late response, but here is a solution to this issue. You need to replace `form` attribute of `backgroundCircle` shape with a custom path:
```
backgroundCircle = Shape(
    form: Path(segments: [
        PathSegment(type: .M, data: [0, 0]),
        PathSegment(type: .m, data: [-fanMenu.radius, 0]),
        PathSegment(type: .a, data: [fanMenu.radius, fanMenu.radius, 0, 1, 0, fanMenu.radius * 2, 0])
    ])
)
```
Result:
![Screen Shot](https://user-images.githubusercontent.com/553051/62047643-3264fa00-b235-11e9-8bf2-488f4e03037a.png)
