### ISSUE TITLE
Change center button image on click on it.  

### ISSUE THREAD

**Issue by Gagan6696** [exyte/fan-menu#43]

**Comment by shipinev** [comment]
Hi @Gagan6696.
If you want to change the menu button image on the user tap event, first of all, you need to update `FanMenuButton` model and switch `image` property to a variable.
Since you always know the menu button identifier, you can use `onItemDidClick` event handler, i.e.:
```
fanMenu.onItemDidClick = {
    if $0.id == "main" {
        $0.id = UIImage(named: "icon-name")
    }
}
```
