### ISSUE TITLE
elements underneath not accessible

### ISSUE THREAD

**Issue by kier70** [exyte/fan-menu#47]
When my instance of the fan menu is closed (the .button is visable bot not .items) the overall bounds seem to be covering elements and preventing user interaction.

**Comment by shipinev** [comment]
Hey @kier70. Could you please provide an example project or maybe more information about your UI elements structure? I tried to reproduce with our example projects, and everything works fine.

**Comment by kier70** [comment]
Apologies, this may have been something to do with the layout of elements in my project - in a new project with minimal elements this doesn't appear to be reproducible
