### ISSUE TITLE
Cannot use a single menu item.

### ISSUE THREAD

**Issue by mtwillet** [exyte/fan-menu#49]
When creating a menu with a single item

_fanViewButton.items = [FanMenuButton(
                                    id: "test",
                                    image: UIImage(named: "Hook"),
                                    color: Color.clear
                                )]_

you get the following error.

_Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem._

Can you give some guidance on how to set it up to use a single menu option?

**Comment by shipinev** [comment]
Hi @mtwillet. Thanks for pointing this out. Fix for this issue added to the master branch and will be included in the upcoming release.
