### ISSUE TITLE
Allowing buttons to show outside view

### ISSUE THREAD

**Issue by kier70** [exyte/fan-menu#50]
I have the following

`swift 
node.place = Transform.move(
            dx: Double(self.frame.width) / 2,
            dy: Double(self.frame.height) + 100
        )`

which takes the fanMenu.button outside the view but is not shown.  Is there a method to allow it show - I looked at clip to bounds with no luck.

**Comment by shipinev** [comment]
Hey @kier70. Could you please attach an example project? It's quite hard to understand the issue with code listing you provided.
