### ISSUE TITLE
semanticContentAttribute not changing for arabic language

### ISSUE THREAD

**Issue by ibhavin** [exyte/fan-menu#51]
I have implemented fanmenu like displayed in [TaskViewController.swift](https://github.com/exyte/fan-menu/blob/master/Example/Example/TaskViewController.swift). It is working good in english language but while change language to arabic fanMenuView is not changing `semanticContentAttribute` to `rigthtToLeft`

**Comment by shipinev** [comment]
Hey @ibhavin. Sorry for the late response. FanMenu doesn't support `semanticContentAttribute` at this point. We are always glad to see new contributors to [Macaw](https://github.com/exyte/Macaw), so you can implement such a feature if interested in it.
Thanks!
