### ISSUE TITLE
Xcode 11.4 / Swift 5.2

### ISSUE THREAD

**Issue by ebeneezer** [exyte/fan-menu#52]
Dear Fan-Menu team,

i am trying out your interesting Pod on CocoaPods - alas it does not seem to compile with Xcode 11.4 Swift 5.2 respectively. Seems some incompatibility with the Macaw library, that was updated for Swift 5.2.

Will there be an update to the FanMenu pod?

Regards,
Mike

**Comment by JuanpabloMacias** [comment]
Dear Fan-Menu team,

The same thing is happening in my project. I get this error in the open class Gradient: Fill.
Error:
Overridden method 'equals' has generic signature <T where T : Gradient> which is incompatible with base method's generic signature <T where T : Fill>; expected generic signature to be <T where T : Fill>

Thank you for your help,
Juanpablo

**Comment by BalthazarJam** [comment]
There’s a fix on github

**Comment by ebeneezer** [comment]
That may be so - question was if the Fan-Menu CocoaPods pod would be updated.

**Comment by shipinev** [comment]
Hey guys. Currently, Swift 5.2 support for Macaw available only in the master branch. Since we depend on the stable Macaw version, we are waiting for the release.

**Comment by BalthazarJam** [comment]
The ‘fix’ is what is required to update the Macaw code that causes the problem with Swift 5.2, hence updating the implementation of the Fan-Menu CocoaPods pod for Swift 5.2.

**Comment by shipinev** [comment]
I have good news for you. Macaw released an update a few days ago.
Don't forget to run `pod update` to update FanMenu dependencies.
