### ISSUE TITLE
Support swift package manager

### ISSUE THREAD

**Issue by perbrondum** [exyte/fan-menu#53]

**Comment by shipinev** [comment]
Hey @perbrondum. I will add Package.swift file during the week. Currently, SPM will be available in the master branch since Macaw doesn't have a version with SPM support yet (master branch only).

**Comment by shipinev** [comment]
@perbrondum SPM support now available in the master branch.

<img width="730" alt="FanMenu SPM" src="https://user-images.githubusercontent.com/553051/80694503-cc2c4100-8afe-11ea-87ff-11bde0cf0363.png">
