### ISSUE TITLE
incomplete warning 

### ISSUE THREAD

**Issue by perbrondum** [exyte/fan-menu#55]
print("WARNING: FanMenu doesn't fit into view bounds. It should be at least \((fanMenu.menuRadius + fanMenu.radius) * 2.0) wide _and in high_")

**Comment by f3dm76** [comment]
@perbrondum Fixed the spelling in master branch, thank you. But why do you say it is "incomplete"? Should I add some info to it?

**Comment by perbrondum** [comment]
'and in high' is incomplete...

**Comment by shipinev** [comment]
I think that the current message is pretty clear. If you want to suggest a more specific message, you could open a pull request. We always glad to see new contributors. :)
I'm closing this issue for now. Thanks!
