### ISSUE TITLE
add method so we can change the image of FanMenuButton

### ISSUE THREAD

**Issue by amirtutunchi** [exyte/fan-menu#57]
Hi 
first of all thanks for this wonderful component, it would be very nice if we could have better access to the image view of FanMenuButton. for example we could change the image or set the font for the title label. I think that way you can not use struct for FanMenuButton

**Comment by shipinev** [comment]
Hey @amirtutunchi.
Glad that you like FanMenu, and thanks for your feedback. I will discuss these API changes with our team.
Thanks!

**Comment by shipinev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FanMenuButton API improvements](https://trello.com/c/bnQ39Fn3/34-fanmenubutton-api-improvements)
