### ISSUE TITLE
Use with SwiftUI

### ISSUE THREAD

**Issue by benstokoe** [exyte/fan-menu#58]
Hey, is it possible to use this with SwiftUI? And how would I use it?

Thanks

**Comment by shipinev** [comment]
Hey @benstokoe.
You might be interested in our SwiftUI version of this library called [FloatingButton](https://github.com/exyte/FloatingButton). 
But if you want to use FanMenu in SwiftUI, you need to implement a wrapper by using [UIViewRepresentable](https://developer.apple.com/documentation/swiftui/uiviewrepresentable) protocol.
I hope this helps you.

**Comment by benstokoe** [comment]
Ah! Sorry I didn't realise that it could do the circle as well! I thought it was only the straight list. My bad. Thanks for getting back to me
